Fix track check

diff --git a/.github/workflows/publish-charm.yaml b/.github/workflows/publish-charm.yaml
--- a/.github/workflows/publish-charm.yaml
+++ b/.github/workflows/publish-charm.yaml
@@ -45,6 +45,13 @@ jobs:
           echo sanitized=$(echo ${{ inputs.branch-name }} | sed 's/[/_.]/-/g' | sed "s/^/\//") >> $GITHUB_OUTPUT
         if: ${{inputs.branch-name}} != ""
 
+      - name: Validate track-name
+        run: |
+          if [ -z "${{ inputs.track-name }}" ]; then
+            echo "Error: track-name cannot be empty"
+            exit 1
+          fi
+
       - name: Upload charm to Charmhub
         uses: canonical/charming-actions/upload-charm@2.6.3
         with:
@@ -52,12 +59,12 @@ jobs:
           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
           github-token: "${{ secrets.GITHUB_TOKEN }}"
           channel: ${{ inputs.track-name }}/edge${{ steps.sanitize.outputs.sanitized }}
-        if: ${{inputs.track-name}} != ""
+        if: ${{inputs.track-name}} != "latest"
 
       - name: Select Charmhub channel
         uses: canonical/charming-actions/channel@2.6.3
         id: channel
-        if: ${{inputs.track-name}} == ""
+        if: ${{inputs.track-name}} == "latest"
 
       - name: Upload charm to Charmhub
         uses: canonical/charming-actions/upload-charm@2.6.3
@@ -66,7 +73,7 @@ jobs:
           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
           github-token: "${{ secrets.GITHUB_TOKEN }}"
           channel: ${{ steps.channel.outputs.channel }}
-        if: ${{inputs.track-name}} == ""
+        if: ${{inputs.track-name}} == "latest"
 
       - name: Publish libs
         uses: canonical/charming-actions/release-libraries@2.6.3
